spring:
   data:
      mongodb:
         username: admin
         password: pass
         host: localhost
         port: 27018
         database: chat_app
         authentication-database: admin
         

